// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gldksyzhosckftzreauz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZGtzeXpob3Nja2Z0enJlYXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODMxNTcsImV4cCI6MjA2NzQ1OTE1N30.QX06rh3owqfBdzuhgHLLIrgab8nb0ewpIwdclPNeeZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});